version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: actorswidget-fe
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - .:/app/node_modules
    stdin_open: true
    tty: true
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    container_name: actorswidget-be
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - .:/app/node_modules